# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  redis:
    container_name: redis
    image: redis:5.0
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    command:
      - "redis-server"
      - "--requirepass password"
volumes:
  - redis_data: