# zk 单节点 + dubbo_admin
version: '3.1'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.7
    restart: always
    hostname: zookeeper
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 2181:2181